#! /bin/bash
# echo "<filename>" | tr '[:upper:]' '[:lower:]' | tr '-' '_'

ARG="$@"

if [ "x${ARG}" = "x" ]; then
	echo -e "[ERROR] -- no filename as argument\n"
	exit
else
	FJLM=$ARG
fi

OUTPUT=$(echo ${FJLM} |  tr '[:upper:]' '[:lower:]' | sed -e 's/: */-/g' -e 's/,//g' -e 's/ \././' | tr '_' '-')
echo "${OUTPUT}" | sed 's/"//g'

