#! /bin/bash

ARG="$@"

if [ "x${ARG}" = "x" ]; then
	echo "[ERROR] -- no string as argument"
	exit
else
	STR=$ARG
fi

OUTPUT=$(echo ${STR} |  tr '[:upper:]' '[:lower:]' | sed -e 's/: */_/g' -e 's/,//g' -e 's/ \././g' | tr ' ' '-')
echo "${OUTPUT}" | sed 's/"//g'
echo "${OUTPUT}" | sed 's/"//g' | putclip     # use xclip on Linux!!

