#! /bin/bash

# echo "<filename>" | tr ' ' '_'

ARG="$@"

if [ "x${ARG}" = "x" ]; then
	echo "[ERROR] -- no string as argument"
	exit
else
	STRNG=$ARG
fi

OUTPUT=$(echo ${STRNG} | sed 's/ \././'  | tr ' ' '_')
echo "${OUTPUT}" | sed 's/"//g'

