#! /bin/bash
# echo "<filename>" | tr ' ' '-'

ARG="$@"

if [ "x${ARG}" = "x" ]; then
	echo -e "[ERROR] -- no string as argument\n"
	exit
else
	STRNG="$ARG"
fi

OUTPUT=$(echo ${STRNG} | sed 's/ \././' | tr ' ' '-')
echo "${OUTPUT}" | sed 's/"//g'

