#! /usr/bin/env bash

choice=$(echo -e "logout\nreboot\nshutdown\nquit" | dmenu -fn 'Iosevka 14' -l 5 -p "logout/poweroff:")

case $choice in
	logout)
		sudo loginctl terminate-user ${USER}
		;;
	
	reboot)
		sudo reboot
		;;
	
	shutdown)
		sudo systemctl poweroff
		;;

	quit)
		exit
		;;

	*)
		exit
	;;
esac


