#! /usr/bin/env bash

unset list
list=()

TODAY=$(date +"%Y%m%d")
NOW=$(date +"%H")
URA=8
SRCDIR="${KNOWLEDGEDB:-/home/rgregor/majstaf/mdbgit/knowledgedb}"

if [ $# -eq 1 ]; then
	if [ $((${NOW} - $1)) -le 0  ]; then
		echo "[ERROR] Time out of range!"
		exit
	fi
	URA=$1
fi

echo -e "\nGetting today's entries:"
echo -e "\tin \"${SRCDIR}\""
echo -e "\tafter: ${URA}:00:00 on $(date +%d/%m/%Y)\n"
read -p "Continue? [y/Y], or <enter> to confitm ... " ans

if [ ! $ans == "Y" ] && [ ! $ans == "y" ]; then
	exit
fi

readarray -t -O "${#list[@]}" list < <(find ${SRCDIR} -newermt "${TODAY} ${URA}:00:00" -type f | grep -v '\.git')

if [ ${#list[@]} -le 0 ]; then
	echo "[INFO] No files found"
	exit
fi

fjls=$(for (( i=0; i<${#list[@]}; i++)); do
	echo "${list[$i]}"
done | fzf -m --reverse)

if [ "x${fjls[0]}" == "x" ]; then
	echo "[INFO] No files selected"
	exit
fi

for FJL in $(echo ${fjls[@]}); do echo $FJL; done | xargs -ro vim -pM

