#! /usr/bin/env python3

# send-2args-gg
# 20240526
# -----------------------

# importing python modules:
import smtplib
import os
import argparse
import sys

# import local email settings:
import send_config_gg as scd

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import datetime as dt

# timestamp
def tms():
    return dt.datetime.now().strftime('%Y%m%d_%H%M%S')


# clear the screen:
os.system('clear')


# START
print("[ {} ] Started: {}".format(tms(), sys.argv[0]))

# Parsing arguments: subject, body:
parser = argparse.ArgumentParser()

parser.add_argument('subject', help='The message [SUBJECT] (between quotes if it contains spaces)')
parser.add_argument('body', help='The [BODY] of the message (between quotes if it contains spaces, or if multiline -- closing with quote sign!)')
args = parser.parse_args()

# Assigning arguments to variables:
gSbj = args.subject
gBdy = args.body

# Inserting a SUBJECT as first line into BODY:
gBdyf = "Subject: " + gSbj + "\n" + gBdy

# Composing a email message: header + body ... 
gMsgf = MIMEMultipart()
gMsgf['From'] = scd.gFrom
# gMsgf['To'] =  scd.gTo
gMsgf['To'] = ', '.join(scd.gTo)
gMsgf['Subject'] = str(gSbj)

gMsgf.attach(MIMEText(gBdyf, 'plain'))


# send email:
print("[ {} ] SENDING MAIL ...".format(tms()))

server = smtplib.SMTP(scd.gSmtp, scd.gPort)
server.starttls()
server.login(scd.gUnm, scd.gPsswd)
gTxt = gMsgf.as_string()
server.sendmail(scd.gFrom, scd.gTo, gTxt)
server.quit()

print("[ {} ] DONE!".format(tms()))

