#! /usr/bin/env bash
# ghgltestpush_mdb
# last change: 20240228_en

rmts=( $(git remote) )

COLOR_SET="\e[1;92m"
COLOR_RESET="\e[0m"

for rmt in "${rmts[@]}"
do
	/usr/bin/git push --dry-run ${rmt} main &> status
	grep 'main' status > /dev/null
	if [[ $? -eq 0 ]]; then
		printf "${COLOR_SET}"
		echo -n "[INFO] git testpush in: $(git remote get-url ${rmt}) ..."
		echo " NEED TO PUSH!!"
		cat status
		rm status > /dev/null
		printf "${COLOR_RESET}"
	else
		echo -n "[INFO] git testpush in: $(git remote get-url ${rmt}) ..."
		echo " nothig to push!"
		rm status > /dev/null
	fi
done

