#! /usr/bin/env bash
# mdbgt_status
# last change: 20241017

HST="mdb"
COLOR_SET="\e[1;92m"
COLOR_RESET="\e[0m"
CURRDIR=$PWD
RPRT=${TMP}/testing_report
> ${RPRT}

get_status() {
	cmd=$1
	OUTPUT=$(${cmd} status)

	echo $OUTPUT | grep -i "git push\|untracked\|modified\|deleted" > /dev/null

	if [[ $? -ne 0 ]]; then
		echo -n "[INFO] checking git status in ${DDD} ..."
		echo " no action required"
	else
		echo "---"
		printf "${COLOR_SET}"
		printf "[REPORT] checking git status in ${DDD} ... NEED TO ADD and/or COMMIT\n" | tee -a ${RPRT}
		printf "${COLOR_RESET}"
		${cmd} status
		echo "---"
	fi
}

echo "========================================"
echo "[INFO] running mdbgt_status ..."
echo "========================================"
cd ~/majstaf/${HST}git/
for DDD in $(find * -maxdepth 0 -type d | grep -v "vlpprs_${HST}"); do
	cd $DDD &> /dev/null

	get_status "/usr/bin/git"
	cd ..
done

# volpejpers
DDD="vlpprs_${HST}"
VOLGITDIR="${HOME}/majstaf/${HST}git/vlpprs_${HST}"
VOLWORKTREE="${HOME}/majstaf/majvolpejpers"
get_status "/usr/bin/git --git-dir=${VOLGITDIR} --work-tree=${VOLWORKTREE}"

printf "${COLOR_SET}"
if [ -s ${RPRT} ]; then
	while read LINE; do
		echo "*** ${LINE} ***"
	done < ${RPRT}
else
	echo "*** [REPORT] No action required ***"
fi
printf "${COLOR_RESET}"

rm ${RPRT} 2>/dev/null
cd ${CURRDIR}

echo ""
