#! /usr/bin/env bash

clear
gr_dejt=$(date +%Y%m%d)

if [ $# -ne 2 ]; then
	echo 'USAGE: <scriptmname> [web-URL] [filename-with-dashes]'
	echo
	exit
fi

gr_weburl="$1"
gr_fjl="$2"
gr_flnm="${gr_fjl}-${gr_dejt}.txt"

printf "%-20s%s\n" "Web URL:" "${gr_weburl}"
printf "%-20s%s\n\n" "filename:" "${gr_flnm}"

read -p "Press <enter> to proceed or <ctrl-c> to quit"

echo "filename: ${gr_flnm}" >> ${gr_flnm}
echo -e "${gr_weburl}\n\n" >> ${gr_flnm}
lynx -dump -width=110 ${gr_weburl} >> ${gr_flnm}
echo -e "\n\n---\n" >> ${gr_flnm}

echo
echo 'DONE!'
echo

