#! /bin/bash

ARG="$@"

if [ "x${ARG}" = "x" ]; then
	echo "[ERROR] -- no string as argument"
	exit
else
	FNAME=$ARG
fi

echo -n "Converting 4 spaces to tabs for file ${FNAME} ... "
sed -i 's/ \{4\}/\t/g' ${FNAME}
echo "[OK]."

