#! /bin/bash

# echo "<filename>" | tr ' ' '_'

if [ $# -ne 1 ]; then
	echo "[ERROR] -- no string as argument"
	exit
else
	STRNG=$1
fi

OUTPUT=$(echo ${STRNG} | tr ' ' '_')
echo "${OUTPUT}" | sed 's/"//g'

