#! /usr/bin/env bash

export KDBWORKTREE="${HOME}/Dropbox/ODPRTO"
export KDBGITDIR="${HOME}/majstaf/d_kdb/knowledgedb.git"

git_dkdb="/usr/bin/git --git-dir=${KDBGITDIR} --work-tree=${KDBWORKTREE}"

echo "[INFO] Push to d_GITHUB ..."
${git_dkdb} push ghkdb main
echo "---"

echo "[INFO] Push to d_GITLAB ..."
${git_dkdb} push glkdb main
echo "---"

