#! /usr/bin/env bash

export DMTSGITDIR="${HOME}/majstaf/d_metsys_git/d_metsys"
export DMTSWORKDIR="${HOME}/majstaf/d_metsys_git/d_metsys_source"

git_dmts="/usr/bin/git --git-dir=${DMTSGITDIR} --work-tree=${DMTSWORKDIR}"

echo "[INFO] Push to d_GITHUB ..."
${git_dmts} push github_dmetsys master
echo "---"

echo "[INFO] Push to d_GITLAB ..."
${git_dmts} push gitlab_dmetsys master
echo "---"

