#! /usr/bin/env bash

export DVOLGITDIR="${HOME}/majstaf/d_vol"
export DVOLWORKDIR="${HOME}/majstaf/majvolpejpers"

git_dvol="/usr/bin/git --git-dir=${DVOLGITDIR} --work-tree=${DVOLWORKDIR}"


echo "[INFO] Push to d_GITHUB ..."
${git_dvol} push github_dvol master
echo "---"

echo "[INFO] Push to d_GITLAB ..."
${git_dvol} push gitlab_dvol master
echo "---"

