#! /usr/bin/env bash

export MDBVOLGITDIR="${HOME}/majstaf/mdbgit/vlpprs_mdb"
export MDBVOLWORKDIR="${HOME}/majstaf/majvolpejpers"

git_dvol="/usr/bin/git --git-dir=${MDBVOLGITDIR} --work-tree=${MDBVOLWORKDIR}"

echo "[INFO] Testpush to d_GITHUB ..."
${git_dvol} push --dry-run git@github.com:r-gregor/vlpprs_mdb.git main
echo "---"

echo "[INFO] Testpush to d_GITLAB ..."
${git_dvol} push --dry-run git@gitlab.com:r-gregor/vlpprs_mdb.git main
echo "---"

