#! /usr/bin/env bash
# last change: 20240216 (en)

for DDD in $(ls -1 ~/majstaf/coding2/testing/); do
	echo "[INFO] Testing git status on ${DDD} ..."
	cd $DDD
	/usr/bin/git status
	cd ${HOME}
	echo -e "---\n"
done


