#! /usr/bin/env bash
# filename: mdbgttestpush
# last edit: 20240227_d

CURRDIR=$PWD
cd ~/majstaf/mdbgit
for DDD in $(find * -maxdepth 0 -type d); do
	echo ""
	echo "*** git testpush in ${DDD} ... ***"
	# cd $DDD &>/dev/null && ~/.local/bin/gpdtestpush && cd ..
	cd $DDD &>/dev/null && ~/.local/bin/gpdtestpush && cd ..
# echo -e "\n---"
done

cd ${CURRDIR}

