#! /usr/bin/env bash
# filename: mdbgt_testpush
# last edit: 20240601_mdb

# COLOR_SET="\e[1;94m"
# COLOR_SET="\e[1;34m"
COLOR_SET="\e[1;38;5;75m"
COLOR_RESET="\e[0m"
DEST=${HOME}/majstaf/mdbgit/
STTS=${TMP}/status2
RPRT=${TMP}/report
> ${STTS}
> ${RPRT}

CURRDIR=$PWD
cd ${DEST}
for DDD in $(find * -maxdepth 0 -type d); do
	echo ""
	printf "${COLOR_SET}"
	echo "*** git testpush in ${DDD} ... ***"
	printf "${COLOR_RESET}"
	cd $DDD &>/dev/null && ~/.local/bin/ghgl_testpush_mdb | tee -a ${STTS}
	grep -i 'pull' ${STTS} > /dev/null
	if [[ $? -eq 0 ]]; then
		echo -e "[INFO] git testpush in: ${DDD} ... NEED TO PULL FROM REMOTE!\n" >> ${RPRT}
	fi
	> ${STTS}
	cd ..
done

echo ""
printf "${COLOR_SET}"
echo "*** REPORT ***"
printf "${COLOR_RESET}"
if [ -s ${RPRT} ]; then
	cat ${RPRT}
else
	echo "[INFO] Nothing to push!"
fi
rm ${RPRT} ${STTS} 2>/dev/null

cd ${CURRDIR}

