#! /usr/bin/env bash
# mdbgt_status
# last change: 20240823


HST="mdb"
COLOR_SET="\e[1;92m"
COLOR_RESET="\e[0m"
CURRDIR=$PWD
RPRT=${TMP}/testing_report
> ${RPRT}


function get_status() {
	cmd=$1
	OUTPUT=$(${cmd} status)

	echo $OUTPUT | grep -i "git push\|untracked\|modified\|deleted" > /dev/null

	if [[ $? -ne 0 ]]; then
		echo -n "[INFO] checking git status in ${DDD} ..."
		echo " no action required"
	else
		echo "---"
		printf "${COLOR_SET}"
		printf "[INFO] checking git status in ${DDD} ... NEED TO ADD and/or COMMIT\n" | tee -a ${RPRT}
		printf "${COLOR_RESET}"
		${cmd} status
		echo "---"
	fi
}

cd ~/majstaf/${HST}git/
for DDD in $(find * -maxdepth 0 -type d | grep -v "vlpprs_${HST}"); do
	cd $DDD &> /dev/null

	get_status "/usr/bin/git"
	cd ..
done

# volpejpers
DDD="vlpprs_${HST}"
VOLGITDIR="${HOME}/majstaf/${HST}git/vlpprs_${HST}"
VOLWORKTREE="${HOME}/majstaf/majvolpejpers"
get_status "/usr/bin/git --git-dir=${VOLGITDIR} --work-tree=${VOLWORKTREE}"

echo ""
printf "${COLOR_SET}"
echo "*** REPORT ***"
printf "${COLOR_RESET}"
if [ -s ${RPRT} ]; then
	cat ${RPRT}
else
	echo "[INFO] No action required"
fi

rm ${RPRT} 2>/dev/null
cd ${CURRDIR}

