#! /usr/bin/env bash
# testing_gtghtestpush_en
# last change: 20240228_ed

CURRDIR=$PWD
cd ${HOME}/majstaf/coding2/testing
for DDD in $(ls -d *); do
	echo "*** git testpush in ${DDD} ... ***"
	cd $DDD &>/dev/null && ${HOME}/.local/bin/ghgl_testpush_mdb && cd ..
	echo ""
done

cd ${CURRDIR}

