#! /usr/bin/env bash
# testing_gtghtestpush_en
# last change: 20240319_d

COLOR_SET="\e[1;94m"
COLOR_RESET="\e[0m"

CURRDIR=$PWD
cd ${HOME}/majstaf/coding2/testing
for DDD in $(ls -d *); do
	printf "${COLOR_SET}"
	echo "*** git testpush in ${DDD} ... ***"
	printf "${COLOR_RESET}"
	cd $DDD &>/dev/null && ${HOME}/.local/bin/ghgl_testpush_mdb && cd ..
	echo ""
done

cd ${CURRDIR}

