#! /usr/bin/env bash
# testing_ghgl_testpush_mdb
# last change: 20241017

# COLOR_SET="\e[1;94m"
COLOR_SET="\e[1;38;5;75m"
COLOR_RESET="\e[0m"
USR="mdb"
DEST=${HOME}/majstaf/coding2/testing
STTS=${TMP}/${USR}_testing_status
RPRT=${TMP}/${USR}_testing_report
> ${STTS}
> ${RPRT}

CURRDIR=$PWD
cd ${DEST}

echo "============================================"
echo "[INFO] running testing_ghgl_testpush_mdb ..."
echo "============================================"
for DDD in $(ls -d *); do
	printf "${COLOR_SET}"
	# echo "*** git testpush in ${DDD} ... ***"
	echo "[INFO] git testpush in ${DDD} ... ***"
	printf "${COLOR_RESET}"
	cd $DDD &>/dev/null && ${HOME}/.local/bin/ghgl_testpush_${USR} | tee -a ${STTS}
	grep -i 'pull' ${STTS} > /dev/null
	if [[ $? -eq 0 ]]; then
		echo "[REPORT] git testpush in: ${DDD} ... NEED TO PULL FROM REMOTE" >> ${RPRT}
	fi
	> ${STTS}
	cd ..
done

printf "${COLOR_SET}"
if [ -s ${RPRT} ]; then
	while read LINE; do
		echo "*** ${LINE} ***"
	done < ${RPRT}
else
	echo "*** [REPORT] No action required ***"
fi
printf "${COLOR_RESET}"
rm ${RPRT} ${STTS} 2>/dev/null

cd ${CURRDIR}

echo ""
