#! /usr/bin/env bash
# testing_ghgl_status_mdb
# last change: 20241216

HST="mdb"
TSTDST=${HOME}/majstaf/coding2/testing
COLOR_SET="\e[1;92m"
COLOR_RESET="\e[0m"
CURRDIR=$PWD

unset msg
unset report
report=()

get_status() {
	cmd=$1
	output=$(echo -n $(${cmd} status))

	echo $output | grep -i "git push\|untracked\|modifiedi\|deleted" > /dev/null

	if [[ $? -ne 0 ]]; then
		echo -n "[INFO] checking git status in ${DDD} ..."
		echo " no action required"
	else
		echo "---"
		printf "${COLOR_SET}"
		# printf "[REPORT] checking git status in ${DDD} ... NEED TO ADD and/or COMMIT\n" | tee -a ${TRPRT}
		msg=$(echo -e "[REPORT] checking git status in ${DDD} ... NEED TO ADD and/or COMMIT\n")
		echo -e "$msg"
		printf "${COLOR_RESET}"
		readarray -t -O "${#report[@]}" report < <(echo -e "$msg")
		${cmd} status
		echo "---"
	fi
}

echo "========================================"
echo "[INFO] running mdbgt_status ..."
echo "========================================"
cd ${TSTDST}
for DDD in $(find * -maxdepth 0 -type d | grep -v "vlpprs_${HST}"); do
	cd $DDD &> /dev/null

	get_status "/usr/bin/git"
	cd ..
done

printf "${COLOR_SET}"
# if [ -s ${TRPRT} ]; then
# 	while read LINE; do
# 		echo "*** ${LINE} ***"
# 	done < ${TRPRT}
# else
# 	echo "*** [REPORT] No action required ***"
# fi
if [ ${#report[@]} -gt 0 ]; then
	for j in $(seq 0 $((${#report[@]} - 1))); do
		echo "*** ${report[$j]} ***"
	done
else
	echo "*** [REPORT] No action required ***"
fi
printf "${COLOR_RESET}"

cd ${CURRDIR}

echo ""

