#! /bin/bash
# echo "<filename>" | tr '[:upper:]' '[:lower:]' | tr ' ' '-'

ARG="$@"

if [ "x${ARG}" = "x" ]; then
# if [ $# -ne 1 ]; then
	echo "[ERROR] -- no filename as argument"
	exit
else
	FJLM=$ARG
fi

OUTPUT=$(echo ${FJLM} |  tr '[:upper:]' '[:lower:]' | sed -e 's/: */_/g' -e 's/,//g' -e 's/ \././g' | tr ' ' '-')
echo "${OUTPUT}" | sed 's/"//g'

