#! /bin/bash

ARG="$@"

if [ "x${ARG}" = "x" ]; then
	echo "[ERROR] -- no filename as argument"
	exit
else
	FNAME="$ARG"
fi

if [ ! -f ${FNAME} ]; then
	echo "[ERROR] -- no such file"
	exit
fi

NEW_FNAME=$(echo ${FNAME} | sed 's/ \././' | tr '_' '-')
mv -v ${FNAME} ${NEW_FNAME}


