#! /usr/bin/env bash
# testing_gtgh_testpush_mdb
# last change: 20240601_mdb

# COLOR_SET="\e[1;94m"
COLOR_SET="\e[1;38;5;75m"
COLOR_RESET="\e[0m"
TDEST=${HOME}/majstaf/coding2/testing
TSTTS=${TMP}/testing_status
TRPRT=${TMP}/testing_report
> ${TSTTS}
> ${TRPRT}

CURRDIR=$PWD
cd ${TDEST}
for DDD in $(ls -d *); do
	echo ""
	printf "${COLOR_SET}"
	echo "*** git testpush in ${DDD} ... ***"
	printf "${COLOR_RESET}"
	cd $DDD &>/dev/null && ${HOME}/.local/bin/ghgl_testpush_mdb | tee -a ${TSTTS}
	grep -i 'pull' ${TSTTS} > /dev/null
	if [[ $? -eq 0 ]]; then
		echo -e "[INFO] git testpush in: ${DDD} ... NEED TO PULL FROM REMOTE!\n" >> ${TRPRT}
	fi
	> ${TSTTS}
	cd ..
done

echo ""
printf "${COLOR_SET}"
echo "*** REPORT ***"
printf "${COLOR_RESET}"
if [ -s ${TRPRT} ]; then
	cat ${TRPRT}
else
	echo "[INFO] Nothing to push!"
fi
rm ${TRPRT} ${TSTTS} 2>/dev/null

cd ${CURRDIR}

